[package]
name = "solana-arb-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.3"
solana-sdk = "1.18.3"
solana-account-decoder = "1.18.3"
tokio = { version = "1.36.0", features = ["full"] }
futures = "0.3.30"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
log = "0.4.21"
env_logger = "0.11.2"
base64 = "0.22.0"
bincode = "1.3.3"
anyhow = "1.0.81"
bytemuck = "1.15.0"
clap = { version = "4.5.3", features = ["derive"] }
dotenv = "0.15.0"
# SPL Token dependencies
spl-token = "4.0.0"
spl-associated-token-account = "2.3.0"
spl-token-2022 = "1.0.0"
tungstenite = "=0.20.1"
rand = "0.9.1"
# Dependencies for async operations and HTTP requests
async-trait = "0.1.74"
once_cell = "1.18.0"   # For HTTP_CLIENT static lazy initialization
tracing = "0.1.37"     # For structured logging
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4.41"
lazy_static = "1.4.0"   # ADDED for legacy use; prefer once_cell for new code
# Orca Whirlpools support
# (Removed dependency! Roll your own struct parsing in /src/dex/whirlpool.rs)
