[package]
name = "solana-arb-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
# Solana
solana-client = "1.18.3"
solana-sdk = "1.18.3"
solana-account-decoder = "1.18.3"

# Async and futures
tokio = { version = "1.36.0", features = ["full"] }
futures = "0.3.30"
async-trait = "0.1.74"
once_cell = "1.18.0"
lazy_static = "1.4.0"

# Serialization and encoding
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
bincode = "1.3.3"
base64 = "0.22.0"
hex = "0.4.3"

# CLI and config
clap = { version = "4.5.3", features = ["derive"] }
dotenv = "0.15.0"

# Error handling and logging
anyhow = "1.0.81"
thiserror = "1.0.57"
log = "0.4.21"
env_logger = "0.11.2"
tracing = "0.1.37"

# HTTP and websocket
reqwest = { version = "0.11", features = ["json"] }
tungstenite = "0.20.1"
url = "2.5.0"

# Time and randomness
chrono = "0.4.41"
rand = "0.9.1"

# Solana SPL Token Support
spl-token = "4.0.0"
spl-associated-token-account = "2.3.0"
spl-token-2022 = "1.0.0"

# Concurrency (optional but highly recommended for shared state)
dashmap = "5.5.3"

# Metrics (if you're exposing Prometheus-compatible endpoints)
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

# Orca Whirlpools: implemented manually via custom parser
# (No dependency — handled in /src/dex/whirlpool.rs)
