//! Data ingestion and caching
// This module was auto-generated by the refactor plan. All legacy webhook/websocket logic is deprecated.
// TODO: Remove or refactor as needed for new server-based hooks.

// No submodules exported (legacy logic removed)
