//! Data ingestion: WebSocket feeds, market data, and price feeds
// This module was auto-generated by the refactor plan. All logic from src/websocket/ and src/streams/ is merged here.
// TODO: Refactor and unify all websocket and stream logic into this file.

// No submodules exported (legacy logic removed)
